/**
 * xHelperAlerts alert relay
 *
 * Bridges Claude Code cloud sessions (claude.ai/code) to the Mac app.
 * The cloud sandbox can't reach the user's machine, so:
 *
 *   cloud Notification hook ──POST /alert──▶ relay ◀──GET /poll── Mac app
 *
 * Each device token gets its own Durable Object (idFromName), so pushes
 * and polls are strongly consistent — no KV edge-cache lag. Tokens are
 * 32+ char random strings generated by the Mac app; possession of the
 * token is the auth.
 *
 * POST /alert?token=T   body: {"title": "...", "message": "..."}  → 204
 * GET  /poll?token=T    → {"alerts": [{title, message, ts}, ...]} (drains)
 */

const TOKEN_RE = /^[A-Za-z0-9_-]{32,128}$/;
const MAX_PENDING = 50; // drop oldest beyond this — poller is gone/asleep
const MAX_BODY_BYTES = 4096;

export class AlertBox {
  constructor(ctx) {
    this.ctx = ctx;
  }

  async fetch(request) {
    const url = new URL(request.url);

    if (request.method === "POST" && url.pathname === "/alert") {
      let title = "xHelperAlerts";
      let message = "Claude needs your attention";
      try {
        const body = await request.json();
        if (typeof body.title === "string" && body.title.trim()) {
          title = body.title.slice(0, 200);
        }
        if (typeof body.message === "string" && body.message.trim()) {
          message = body.message.slice(0, 500);
        }
      } catch {
        // Missing/malformed JSON → keep defaults; an alert with a generic
        // message still beats a silently dropped one.
      }
      const pending = (await this.ctx.storage.get("pending")) ?? [];
      pending.push({ title, message, ts: Date.now() });
      while (pending.length > MAX_PENDING) pending.shift();
      await this.ctx.storage.put("pending", pending);
      return new Response(null, { status: 204 });
    }

    if (request.method === "GET" && url.pathname === "/poll") {
      const pending = (await this.ctx.storage.get("pending")) ?? [];
      if (pending.length > 0) await this.ctx.storage.delete("pending");
      return Response.json({ alerts: pending });
    }

    return new Response("not found", { status: 404 });
  }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/healthz") {
      return new Response("ok");
    }

    if (url.pathname !== "/alert" && url.pathname !== "/poll") {
      return new Response("not found", { status: 404 });
    }

    const token = url.searchParams.get("token") ?? "";
    if (!TOKEN_RE.test(token)) {
      return new Response("bad token", { status: 400 });
    }

    // Cheap guard before the DO hop — reject oversized pushes early.
    const len = Number(request.headers.get("content-length") ?? 0);
    if (len > MAX_BODY_BYTES) {
      return new Response("too large", { status: 413 });
    }

    const stub = env.ALERT_BOX.get(env.ALERT_BOX.idFromName(token));
    return stub.fetch(request);
  },
};
